server {
  listen 80;
  location / {
    root /var/www/html;
    index index.html;
    try_files $uri $uri/ /index.html;
  }

  location /regions {
    proxy_pass http://cities-backend:3001;
  }

  location /municipalities {
    proxy_pass http://cities-backend:3001;
  }

  location /cities {
    proxy_pass http://cities-backend:3001;
  }
}